### ISSUE TITLE
Can't create new characters.

### ISSUE THREAD

**Issue by walterbishop100** [Muttley/foundryvtt-ac2d20#102]
Before and after v12 upload, the create new character option allows the name to be typed in, but no characters are added to the list.  Same for NPCs.  Some character sheets popup, but not all.  Picture import for tokens isn't working either.   I can create new vehicles and scenes, just not new characters.

**Comment by Muttley** [comment]
Do you have any mods enabled?.  Creating a character works just fine here on v12.

Check the console for errors.

**Comment by walterbishop100** [comment]
Thanks for getting back to me.  So I know now it isn't an update issue for
ac2d20, that helps.

No mods to the game.  Here is what is happening.  I copied the most recent
URL 11.5.3 - the one at the top of the list.
On my Foundry screen, it has the ac2d20 at 11.3.0.  When I updated with the
new URL it says it is already updated and remains at 11.3.0.
I uninstalled and recreated the world and it still reads 11.3.0.

At on point it did go green and read 11.5.3, then it changed back to yellow
11.3.0.  This was after I posted my question, so it's something on my end.
I'll clear the cache and see if that helps.  I'll post in github if that
works or if something else did.

Thanks again,

Walter

**Comment by Muttley** [comment]
You shouldn't need to install manually via a URL at all.  Just go into the Game Systems section of the Foundry launcher and install the game from the list there:

![image](https://github.com/Muttley/foundryvtt-ac2d20/assets/853835/adbc6cd0-6b1e-49c3-b995-570e1c539492)

I would uninstall the system and then reinstall via the menu.

**Comment by walterbishop100** [comment]
Thanks.  I started that and when I went to uninstall, it said I didn't have
permission or had to 'unlink.'  I sent that to my server admin (not forge),
and he had manually updated the system to v12.  He changed a permission for
me so I wasn't able to do that.  He changed that and it updated.
Everything works!  Thank You!

Walter

**Comment by Muttley** [comment]
OK, so it sounds like it was a server configuration error then.

I'm glad you've got things working now.

Have fun.
