### ISSUE TITLE
GM Threat "-" button not working

### ISSUE THREAD

**Issue by tak5haka** [Muttley/foundryvtt-ac2d20#118]
https://github.com/Muttley/foundryvtt-ac2d20/assets/40823406/176ee386-f65b-493e-85d6-917074909eba

When clicking on the "-" button on the GM Threat box, nothing happens. No errors are posted to console either, so not sure what is going on. The "+" works fine and the Party Momentum "+" and "-" work as expected. Have attached a short video.

Foundry v11.315
AC2D20 v 11.6.2

Same on Foundry v12.327 (no modules)

**Comment by trombonecot** [comment]
also happened to me

**Comment by theczarek** [comment]
same here
