### ISSUE TITLE
Focus "checkmark" does not stay selected once window is closed

### ISSUE THREAD

**Issue by duffie563** [Muttley/foundryvtt-ac2d20#134]
Foundry Virtual Tabletop: Version 12 Stable, 12.331
Game System: ac2d20, 11.6.3
Active Modules: 10
Performance Mode: 2

OS: Windows 15.0.0 x86 (64-bit)
Client: Not(A:Brand/24.0.0.0
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3090 (0x00002204) Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 1920 x 1080 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 0
Largest Texture: 1920 x 1080 

Actors: 1 | Items: 0 | Journal Entries: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 8 | Chat Messages: 7

World Scripts: 

Using the included character sheet - adding PREGENS to world - Added 2 characters to test issue - Selected a skill and then expertise - Check focus box - close window - reopen and checkmark is gone.

Anything else needed, please let me know.

**Comment by duffie563** [comment]
Even created new world, no addons.. same issue

**Comment by Muttley** [comment]
I've been unable to replicate this.  Are you seeing any errors in the console (F12 to get the dev tools up)?

Would it be possible to attach a copy of your world having the problem so I can look to see if there's anything weird going on there?

**Comment by duffie563** [comment]
Console - A warning but was there before I did anything
foundry-esm.js:4621 Error: You are accessing the global "Die" which is now namespaced under foundry.dice.terms.Die
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at get (foundry-esm.js:66690:25)
    at DieACChallenge.mjs:1:45

World download - https://1drv.ms/u/c/5e51cdce913dbb71/EVnSIOuDTIRCiCBGQGZp6KMB25TKWdTBk85tZpVTfLqGwg?e=K9n2V0

**Comment by Muttley** [comment]
This is extremely odd, your world works fine here as well.

You don't happen to have your Foundry data folder in a cloud synced location do you (Dropbox or Onedrive)?  Maybe something is messing with the DB file?

**Comment by duffie563** [comment]
No, but Foundry's data folder resides in the same root folder where OneDrive's folder is located... see picture attachment

![folders](https://github.com/user-attachments/assets/cd1c35ed-5d18-421b-aa0b-4bb5b7924d38)

Think that may be an issue?

**Comment by Muttley** [comment]
As it's not in actually in the OneDrive folder I wouldn't have thought so, although if you can move it elsewhere for testing it would be interesting to see.

Could it be a permissions issue?  You could try running Foundry VTT as Administrator as a one-off to see if that makes any difference.

Do you have similar issues with any other systems?

**Comment by duffie563** [comment]
Negative on both....damn.... Moved data to another drive, and ran Foundry as admin...

**Comment by Muttley** [comment]
You could try reinstalling just the system for starters.

If that Windows 11 BTW?  I've only got a Windows 10 machine for testing at the moment.

**Comment by duffie563** [comment]
Will do... Yes Windows 11

**Comment by duffie563** [comment]
No change!! Uninstalled, removed install and old data folders. Reinstalled new location and new data folder. Only Foundry and AC ruleset installed....Ran as admin too...

**Comment by duffie563** [comment]
Installed on Win 11 laptop that's never had Foundry on it, same issue...

**Comment by duffie563** [comment]
I will say the "checkmark" roll works, rolled two 1s and got 6 successes registered in chat log...

**Comment by Muttley** [comment]
> CLOSE the case please!!! It DOES work, I was not selecting the checkmark in the proper window. Didn't see the modify selection hover if you right click on a skill... My apologies!!! Back to work!!

Yeah, you need to edit the actual skill item.  Were you clicking the Focus in the roll dialog by mistake?

FYI, there's also a shortcut to check focuses.  Hold the Ctrl key down and left-click focuses displayed on the character sheet to toggle them on/off.

Regardless, I'm glad you're up and running.

Have fun.
