### ISSUE TITLE
Automatic update of char sheet

### ISSUE THREAD

**Issue by lozanoje** [Muttley/foundryvtt-ac2d20#31]
Calculate derived stats: stress
Calculate bonus to attributes
Calculate redution to stress due to fatigue
Calculate injuries.count based on injury1.text, injury2.text and injury3.text, also for injuries.treated - might be useful for tracking-resources modules like Bar Brawl

**Comment by Muttley** [comment]
Splitting this into multiple tickets for clarity:

- [ ] #54
- [ ] #55
- [ ] #57
