### ISSUE TITLE
Add languages field to character sheet

### ISSUE THREAD

**Issue by lozanoje** [Muttley/foundryvtt-ac2d20#33]
Being a game of travelling across the world and having to infiltrate in multiple regions with multiple languages, i think "languages" is worth its own field in the character sheet.

Maybe along with Nationality, Background, etc. or whitin its individual space as Wounds with + button to add new ones.

**Comment by Muttley** [comment]
Spoken languages are actually classed as truths in the game, so they should go in the Personal Truths & Scars section.

**Comment by lozanoje** [comment]
Yes, but its got its own field in the pc sheet:

![](https://i.ibb.co/XW0nXz7/2024-05-26-07-45-25.jpg)

As you might have a second language (if GM allows) 
+ bonus languages based on your Reason Score
+ up to 3 additional languages if Linguistics/Polyglot

This might fill up the truths section, so probably this is why its got its own space at the pc sheet.

**Comment by Muttley** [comment]
> Yes, but its got its own field in the pc sheet:
> 
> ![](https://camo.githubusercontent.com/d83b65b59f4c41eef62c83551be48ef2add6d12a77e8e81aaddac2ba4f87cabc/68747470733a2f2f692e6962622e636f2f5857306e587a372f323032342d30352d32362d30372d34352d32352e6a7067)
> 
> As you might have a second language (if GM allows) plus bonus languages based on your Reason Score plus up to 3 additional languages if Linguistics/Polyglot
> 
> This might fill up the truths section, so probably this is why its got its own space at the pc sheet.

Yep, you're right.  I think I had a senior moment, and for some reason failed to see that section on the character sheet.  ;)
