### ISSUE TITLE
Update flat injuries values for standard character so they can be utilised by macros or modules

### ISSUE THREAD

**Issue by Muttley** [Muttley/foundryvtt-ac2d20#57]
`system.injuries.value` = number of untreated injuries
`system.injuries.treated` = number of treated injuries

**Comment by lozanoje** [comment]
Hi, 

Does this ever worked as expected? Seems that system.injuries.value  and system.injuries.treated are not updated.

![2024-06-02 18_30_44-C__Users_Jose Lozano_Downloads_fvtt-Actor-agente-daphne-rogers-BCXmd8QfWoCTrQz2 ](https://github.com/Muttley/foundryvtt-ac2d20/assets/97222117/99b29364-70ca-4e4f-a9af-efa861c62e51)

**Comment by Muttley** [comment]
It's dynamically calculated while preparing the character and not stored in the actor.  Those two keys are also used by NPCs though.

**Comment by lozanoje** [comment]
Mmm, ok, i think i need to learn a lot more about Foundry development since I get lost easily with those concepts. Anyway, looks like it is working on 11.5.2 - probably a marginal temp error by my side. Thanks!
