### ISSUE TITLE
Hardcoded skills in autocalc MaxStress

### ISSUE THREAD

**Issue by lozanoje** [Muttley/foundryvtt-ac2d20#66]
The function searchs for the skill Resilience:

`	_calculateMaxStress() {
...
			i => i.type === "skill" && i.name === "Resilience"
		);`

I use custom skills in spanish, so Resilience is 

`      "img": "systems/ac2d20/assets/skills.svg",
      "name": "Fortaleza",
      "type": "skill",`

And produces this error:

![2024-05-28 00_05_34-Foundry Virtual Tabletop - Personal_ Microsoft​ Edge](https://github.com/Muttley/foundryvtt-ac2d20/assets/97222117/5c3640cc-f7a9-46a2-8602-7b1c660d1682)

**Comment by Muttley** [comment]
You don't need to use custom skills for translation purposes any more as the default ones are automatically translated if necessary.  Custom skills are now purely for if you want to add your own additional skills and if so you use a copy of the base skills to start with.

**Comment by lozanoje** [comment]
I dont like the idea of using system english skills for two reasons:
+Skills compendium is not translated itself (appears in english, so for spanish user it keeps appearing Resilience instead of Fortaleza if someone want to search compendia for Fortaleza) - i know this is a little minor detail 
+I lose the spanish description of each skill and focus in the skill item, there is no way of adding spanish description and case-use of each skill if I use the i18n

**Comment by Muttley** [comment]
> Or going definitively for system skills, removing the skill-compendium setting, you can always draganddrop custom skills whenever needed

This is probably the way forward now everything is translated properly.

**Comment by Muttley** [comment]
@lozanoje I'm probably going ahead with retiring the custom skills for the next release (which will probably only be a few days).

As there's no easy way for me to migrate character skills data, I'm thinking of the following migration steps to run automatically:

- Go through each Character and NPC and find any non-standard skills (ie. names don't match exactly), and if found:

	* Capture the skill name, value and list of tagged Focuses for later
	* Delete the skill from the character

- Add any "missing" skills from the core set
- Output a message to chat with the character name and a listing of the skills that were removed by their original name, showing each one's value and a list of tagged focuses (one message per character).

Does that sound OK to you?  That should at least reduce the amount of work required by the GM after updating the system.

**Comment by lozanoje** [comment]
> @lozanoje I'm probably going ahead with retiring the custom skills for the next release (which will probably only be a few days).
> 
> As there's no easy way for me to migrate character skills data, I'm thinking of the following migration steps to run automatically:
> 
> * Go through each Character and NPC and find any non-standard skills (ie. names don't match exactly), and if found:
>   
>   * Capture the skill name, value and list of tagged Focuses for later
>   * Delete the skill from the character
> * Add any "missing" skills from the core set
> * Output a message to chat with the character name and a listing of the skills that were removed by their original name, showing each one's value and a list of tagged focuses (one message per character).
> 
> Does that sound OK to you? That should at least reduce the amount of work required by the GM after updating the system.

I made it automatically outside Foundry, used foundry-cli to export all actors and then I programmed the replacement of each skill in spanish back to english in every file and then I packed it again.

Probably best option is: take skill names from world's language file (es.json), find the counterparts in english (en.json) and replace, then list the missing skills

I dont know how many users has their custom skills, probably only spanish users (due to the skill compendium i provided with my translation module)

Fully updated spanish file is at: https://github.com/lozanoje/fvtt-module-ac2d20-es/blob/main/lang/es.json including new tooltip feature, I will try to send you a PR with this updated file

**Comment by Muttley** [comment]
Resolved by the data migration in the next release
