### ISSUE TITLE
Skill localization not working on NPCs

### ISSUE THREAD

**Issue by lozanoje** [Muttley/foundryvtt-ac2d20#71]
Looks like skill names in NPCs are not translated. Focuses works fine.

For PCs both works well:

![Image](https://github.com/Muttley/foundryvtt-ac2d20/assets/97222117/b829577b-d984-4b5d-8f3d-508b2a5ff852)

**Comment by lozanoje** [comment]
I think this solves the issue, i have to check it tomorrow:

https://github.com/lozanoje/foundryvtt-ac2d20/commit/7363f77b19956e908409b4d9286ed3dfe9e46aa4

**Comment by Muttley** [comment]
> I think this solves the issue, i have to check it tomorrow:
> 
> [lozanoje@7363f77](https://github.com/lozanoje/foundryvtt-ac2d20/commit/7363f77b19956e908409b4d9286ed3dfe9e46aa4)

Yeah, that's exactly the fix.
